baseURL: "https://zayd.fun/"
title: "zayd's corner"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Portfolio
      url: portfolio/
      weight: 1
    - name: Contact
      url: contact/
      weight: 2
    - name: Blog
      url: https://rectitudes.substack.com
      weight: 3

params:
  description: "This website hosts zayd mahmud's portfolio, socials, and contact information."
  author: zayd mahmud
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: dark
  hideFooter: true
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  hideAuthor: true
  profileMode:
    enabled: true
    title: Hey! I'm Zayd Mahmud.
    subtitle: "I'm a senior at Plano West Senior High School. I'm academically interested in philosophy, economics, and information technology. I compete in and coach debate at the national level, speak and organize various events in my community, and used to work as a freelance 3D generalist for over half a decade."
    imageUrl: "icon.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Portfolio
        url: portfolio/
      - name: Contact
        url: contact/
      - name: Blog
        url: https://rectitudes.substack.com
  socialIcons:
    - name: CV
      url: cv.pdf
    - name: LinkedIn
      url: https://linkedin.com/in/zayd-mahmud-879409300/
    - name: Instagram
      url: https://instagram.com/zayd.m4
    - name: Twitter
      url: https://x.com/zira3d
    - name: GitHub
      url: https://github.com/zaydm4
  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "zayd mahmud"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

module:
  imports:
    - path: github.com/rootwork/hugo-module-gallery-grid
